// ISO_639-1
const iso6391List = {
  en: [
    ["ab", "Abkhazian"],
    ["aa", "Afar"],
    ["af", "Afrikaans"],
    ["ak", "Akan"],
    ["sq", "Albanian"],
    ["am", "Amharic"],
    ["ar", "Arabic"],
    ["an", "Aragonese"],
    ["hy", "Armenian"],
    ["as", "Assamese"],
    ["av", "Avaric"],
    ["ae", "Avestan"],
    ["ay", "Aymara"],
    ["az", "Azerbaijani"],
    ["bm", "Bambara"],
    ["ba", "Bashkir"],
    ["eu", "Basque"],
    ["be", "Belarusian"],
    ["bn", "Bengali"],
    ["bi", "Bislama"],
    ["bs", "Bosnian"],
    ["br", "Breton"],
    ["bg", "Bulgarian"],
    ["my", "Burmese"],
    ["ca", "Catalan, Valencian"],
    ["ch", "Chamorro"],
    ["ce", "Chechen"],
    ["ny", "Chichewa, Chewa, Nyanja"],
    ["zh", "Chinese"],
    [
      "cu",
      "Church Slavic, Old Slavonic, Church Slavonic, Old Bulgarian, Old Church Slavonic",
    ],
    ["cv", "Chuvash"],
    ["kw", "Cornish"],
    ["co", "Corsican"],
    ["cr", "Cree"],
    ["hr", "Croatian"],
    ["cs", "Czech"],
    ["da", "Danish"],
    ["dv", "Divehi, Dhivehi, Maldivian"],
    ["nl", "Dutch, Flemish"],
    ["dz", "Dzongkha"],
    ["en", "English"],
    ["eo", "Esperanto"],
    ["et", "Estonian"],
    ["ee", "Ewe"],
    ["fo", "Faroese"],
    ["fj", "Fijian"],
    ["fi", "Finnish"],
    ["fr", "French"],
    ["fy", "Western Frisian"],
    ["ff", "Fulah"],
    ["gd", "Gaelic, Scottish Gaelic"],
    ["gl", "Galician"],
    ["lg", "Ganda"],
    ["ka", "Georgian"],
    ["de", "German"],
    ["el", "Greek, Modern (1453–)"],
    ["kl", "Kalaallisut, Greenlandic"],
    ["gn", "Guarani"],
    ["gu", "Gujarati"],
    ["ht", "Haitian, Haitian Creole"],
    ["ha", "Hausa"],
    ["he", "Hebrew"],
    ["hz", "Herero"],
    ["hi", "Hindi"],
    ["ho", "Hiri Motu"],
    ["hu", "Hungarian"],
    ["is", "Icelandic"],
    ["io", "Ido"],
    ["ig", "Igbo"],
    ["id", "Indonesian"],
    ["ia", "Interlingua (International Auxiliary Language Association)"],
    ["ie", "Interlingue, Occidental"],
    ["iu", "Inuktitut"],
    ["ik", "Inupiaq"],
    ["ga", "Irish"],
    ["it", "Italian"],
    ["ja", "Japanese"],
    ["jv", "Javanese"],
    ["kn", "Kannada"],
    ["kr", "Kanuri"],
    ["ks", "Kashmiri"],
    ["kk", "Kazakh"],
    ["km", "Central Khmer"],
    ["ki", "Kikuyu, Gikuyu"],
    ["rw", "Kinyarwanda"],
    ["ky", "Kirghiz, Kyrgyz"],
    ["kv", "Komi"],
    ["kg", "Kongo"],
    ["ko", "Korean"],
    ["kj", "Kuanyama, Kwanyama"],
    ["ku", "Kurdish"],
    ["lo", "Lao"],
    ["la", "Latin"],
    ["lv", "Latvian"],
    ["li", "Limburgan, Limburger, Limburgish"],
    ["ln", "Lingala"],
    ["lt", "Lithuanian"],
    ["lu", "Luba-Katanga"],
    ["lb", "Luxembourgish, Letzeburgesch"],
    ["mk", "Macedonian"],
    ["mg", "Malagasy"],
    ["ms", "Malay"],
    ["ml", "Malayalam"],
    ["mt", "Maltese"],
    ["gv", "Manx"],
    ["mi", "Maori"],
    ["mr", "Marathi"],
    ["mh", "Marshallese"],
    ["mn", "Mongolian"],
    ["na", "Nauru"],
    ["nv", "Navajo, Navaho"],
    ["nd", "North Ndebele"],
    ["nr", "South Ndebele"],
    ["ng", "Ndonga"],
    ["ne", "Nepali"],
    ["no", "Norwegian"],
    ["nb", "Norwegian Bokmål"],
    ["nn", "Norwegian Nynorsk"],
    ["ii", "Sichuan Yi, Nuosu"],
    ["oc", "Occitan"],
    ["oj", "Ojibwa"],
    ["or", "Oriya"],
    ["om", "Oromo"],
    ["os", "Ossetian, Ossetic"],
    ["pi", "Pali"],
    ["ps", "Pashto, Pushto"],
    ["fa", "Persian"],
    ["pl", "Polish"],
    ["pt", "Portuguese"],
    ["pa", "Punjabi, Panjabi"],
    ["qu", "Quechua"],
    ["ro", "Romanian, Moldavian, Moldovan"],
    ["rm", "Romansh"],
    ["rn", "Rundi"],
    ["ru", "Russian"],
    ["se", "Northern Sami"],
    ["sm", "Samoan"],
    ["sg", "Sango"],
    ["sa", "Sanskrit"],
    ["sc", "Sardinian"],
    ["sr", "Serbian"],
    ["sn", "Shona"],
    ["sd", "Sindhi"],
    ["si", "Sinhala, Sinhalese"],
    ["sk", "Slovak"],
    ["sl", "Slovenian"],
    ["so", "Somali"],
    ["st", "Southern Sotho"],
    ["es", "Spanish, Castilian"],
    ["su", "Sundanese"],
    ["sw", "Swahili"],
    ["ss", "Swati"],
    ["sv", "Swedish"],
    ["tl", "Tagalog"],
    ["ty", "Tahitian"],
    ["tg", "Tajik"],
    ["ta", "Tamil"],
    ["tt", "Tatar"],
    ["te", "Telugu"],
    ["th", "Thai"],
    ["bo", "Tibetan"],
    ["ti", "Tigrinya"],
    ["to", "Tonga (Tonga Islands)"],
    ["ts", "Tsonga"],
    ["tn", "Tswana"],
    ["tr", "Turkish"],
    ["tk", "Turkmen"],
    ["tw", "Twi"],
    ["ug", "Uighur, Uyghur"],
    ["uk", "Ukrainian"],
    ["ur", "Urdu"],
    ["uz", "Uzbek"],
    ["ve", "Venda"],
    ["vi", "Vietnamese"],
    ["vo", "Volapük"],
    ["wa", "Walloon"],
    ["cy", "Welsh"],
    ["wo", "Wolof"],
    ["xh", "Xhosa"],
    ["yi", "Yiddish"],
    ["yo", "Yoruba"],
    ["za", "Zhuang, Chuang"],
    ["zu", "Zulu"],
    ["unknown", "Unknown"],
  ],
  ru: [
    ["ab", "Абхазский"],
    ["aa", "Афар"],
    ["af", "Африкаанс"],
    ["ak", "Акан"],
    ["sq", "Албанский"],
    ["am", "Амхарский"],
    ["ar", "Арабский"],
    ["an", "Арагонский"],
    ["hy", "Армянский"],
    ["as", "Ассамский"],
    ["av", "Аварик"],
    ["ae", "Авестийский"],
    ["ay", "Аймара"],
    ["az", "Азербайджанский"],
    ["bm", "Бамбара"],
    ["ba", "Башкирский"],
    ["eu", "Баскский"],
    ["be", "Белорусский"],
    ["bn", "Бенгальский"],
    ["bi", "Бислама"],
    ["bs", "Боснийский"],
    ["br", "Бретонский"],
    ["bg", "Болгарский"],
    ["my", "Бирманский"],
    ["ca", "Каталонский, Валенсийский"],
    ["ch", "Чаморро"],
    ["ce", "Чеченский"],
    ["ny", "Чичева, Чева, Ньянджа"],
    ["zh", "Китайский"],
    [
      "cu",
      "Церковнославянский, Старославянский, Церковнославянский, Староболгарский, Старославянский",
    ],
    ["cv", "Чувашский"],
    ["kw", "Корнуолл"],
    ["co", "Корсиканский"],
    ["cr", "Кри"],
    ["hr", "Хорватский"],
    ["cs", "Чешский"],
    ["da", "Датский"],
    ["dv", "Дивехи, Дивехи, Мальдивская"],
    ["nl", "Голландский, Фламандский"],
    ["dz", "Дзонгка"],
    ["en", "Английский"],
    ["eo", "Эсперанто"],
    ["et", "Эстонский"],
    ["ee", "Эве"],
    ["fo", "Фарерский"],
    ["fj", "Фиджийский"],
    ["fi", "Финский"],
    ["fr", "Французский"],
    ["fy", "Западно-Фризский"],
    ["ff", "Фула"],
    ["gd", "Гэльский, Шотландский Гэльский"],
    ["gl", "Галисийский"],
    ["lg", "Ганда"],
    ["ka", "Грузинский"],
    ["de", "Немецкий"],
    ["el", "Греческий, Современный (1453–)"],
    ["kl", "Калааллисут, Гренландский"],
    ["gn", "Гуарани"],
    ["gu", "Гуджарати"],
    ["ht", "Гаитянский, Гаитянский Креольский"],
    ["ha", "Хауса"],
    ["he", "Иврит"],
    ["hz", "Гереро"],
    ["hi", "Хинди"],
    ["ho", "Хири Моту"],
    ["hu", "Венгерский Язык"],
    ["is", "Исландский"],
    ["io", "Я Делаю"],
    ["ig", "Игбо"],
    ["id", "Индонезийский"],
    ["ia", "Интерлингва (Международная Ассоциация Вспомогательных Языков)"],
    ["ie", "Интерлингв, Западный"],
    ["iu", "Инуктитут"],
    ["ik", "Инупиак"],
    ["ga", "Ирландский"],
    ["it", "Итальянский"],
    ["ja", "Японский"],
    ["jv", "Яванский"],
    ["kn", "Каннада"],
    ["kr", "Канури"],
    ["ks", "Кашмири"],
    ["kk", "Казахский"],
    ["km", "Центральный Кхмерский"],
    ["ki", "Кикуйю, Гикуйю"],
    ["rw", "Киньярванда"],
    ["ky", "Киргизский"],
    ["kv", "Коми"],
    ["kg", "Конго"],
    ["ko", "Корейский"],
    ["kj", "Куаньяма, Кваньяма"],
    ["ku", "Курдский"],
    ["lo", "Лаосский"],
    ["la", "Латинский"],
    ["lv", "Латышский Язык"],
    ["li", "Лимбургский, Лимбургский, Лимбургский"],
    ["ln", "Лингала"],
    ["lt", "Литовский Язык"],
    ["lu", "Люба-Катанга"],
    ["lb", "Люксембургский, Летзебургский"],
    ["mk", "Македонский"],
    ["mg", "Малагасийский"],
    ["ms", "Малайский"],
    ["ml", "Малаялам"],
    ["mt", "Мальтийский"],
    ["gv", "Мэнкс"],
    ["mi", "Маори"],
    ["mr", "Маратхи"],
    ["mh", "Маршалловский"],
    ["mn", "Монгольский"],
    ["na", "Науру"],
    ["nv", "Навахо, Навахо"],
    ["nd", "Северный Ндебеле"],
    ["nr", "Южный Ндебеле"],
    ["ng", "Ндонга"],
    ["ne", "Непальский"],
    ["no", "Норвежский"],
    ["nb", "Норвежский Букмол"],
    ["nn", "Норвежский Нюнорск"],
    ["ii", "Сычуань И, Нуосу"],
    ["oc", "Окситанский"],
    ["oj", "Оджибва"],
    ["or", "Ория"],
    ["om", "Оромо"],
    ["os", "Осетин, Осетин"],
    ["pi", "Пали"],
    ["ps", "Пушту, Пушту"],
    ["fa", "Персидский"],
    ["pl", "Польский"],
    ["pt", "Португальский"],
    ["pa", "Пенджаби, Пенджаби"],
    ["qu", "Кечуа"],
    ["ro", "Румынский, Молдавский, Молдавский"],
    ["rm", "Ретороманский"],
    ["rn", "Рунди"],
    ["ru", "Русский"],
    ["se", "Северные Саамы"],
    ["sm", "Самоанский"],
    ["sg", "Санго"],
    ["sa", "Санскрит"],
    ["sc", "Сардинский"],
    ["sr", "Сербский"],
    ["sn", "Шона"],
    ["sd", "Синдхи"],
    ["si", "Сингальский, Сингальский"],
    ["sk", "Словацкий"],
    ["sl", "Словенский"],
    ["so", "Сомалийский"],
    ["st", "Южный Сото"],
    ["es", "Испанский, Кастильский"],
    ["su", "Суданский"],
    ["sw", "Суахили"],
    ["ss", "Свати"],
    ["sv", "Шведский"],
    ["tl", "Тагальский"],
    ["ty", "Таитянский"],
    ["tg", "Таджикский"],
    ["ta", "Тамильский"],
    ["tt", "Татарин"],
    ["te", "Телугу"],
    ["th", "Тайский"],
    ["bo", "Тибетский"],
    ["ti", "Тигринья"],
    ["to", "Тонга (Острова Тонга)"],
    ["ts", "Цонга"],
    ["tn", "Тсвана"],
    ["tr", "Турецкий"],
    ["tk", "Туркменский"],
    ["tw", "Тви"],
    ["ug", "Уйгурский, Уйгурский"],
    ["uk", "Украинский"],
    ["ur", "Урду"],
    ["uz", "Узбекский"],
    ["ve", "Венда"],
    ["vi", "Вьетнамский"],
    ["vo", "Волапюк"],
    ["wa", "Валлонский"],
    ["cy", "Валлийский"],
    ["wo", "Волоф"],
    ["xh", "Коса"],
    ["yi", "Идиш"],
    ["yo", "Йоруба"],
    ["za", "Чжуан, Чуан"],
    ["zu", "Зулу"],
    ["unknown", "Неизвестный"],
  ],
};

let iso6391 = null;

const sortFunc = (a, b) => {
  if (a[1] < b[1]) return -1;
  if (a[1] > b[1]) return 1;
  return 0;
};

const getLang = (locale) => {
  if (!iso6391) {
    iso6391 = {
      en: Object.fromEntries(iso6391List.en.sort(sortFunc)),
      ru: Object.fromEntries(iso6391List.ru.sort(sortFunc)),
    };
  }
  let lc = iso6391[locale] ? locale : "en";
  return iso6391[lc];
};

export default getLang;
